// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewBot.Persistence;

#nullable disable

namespace ReviewBot.Persistence.Migrations
{
    [DbContext(typeof(ReviewBotDbContext))]
    [Migration("20260523184735_AddPrReviewState")]
    partial class AddPrReviewState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ReviewBot.Persistence.Entities.DeliveryRecord", b =>
                {
                    b.Property<string>("DeliveryId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeliveryId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("ReviewBot.Persistence.Entities.PrReviewStateRecord", b =>
                {
                    b.Property<long>("InstallationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoFullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PullNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("InstallationId", "RepoFullName", "PullNumber");

                    b.ToTable("PrReviewStates");
                });
#pragma warning restore 612, 618
        }
    }
}
